### ISSUE TITLE
How to define more than 3 "frontend layouts"

### ISSUE THREAD

**Issue by dimitristaufer** [TYPO3-Initiatives/nuxt-typo3#144]
Hello, I have a quick question. According to your [documentation](https://typo3-initiatives.github.io/nuxt-typo3/frontend/layouts.html#define-your-frontend-layout) it is possible to define frontend layouts. This seems to be working just fine on my side.

I am not very familiar with Typo3 and noticed that there are three layout options to choose from by default "layout1, layout2, layout3". Where are these layouts defined? And more importantly, how can I add more layouts in the Typo3 Backend?

Thanks in advance.
Dimitri

**Comment by kubilaymelnikov** [comment]
I hope this helps:

```tsconfig
TCEFORM {
  pages {
    layout {
      altLabels {
        0 =  New Default Name
        1 =  New Layout 1 Name
      }
      removeItems = 2,3
      addItems {
        4 = New Layout 4
        5 = New Layout 5
      }
    }
  }
}
```

[Referenz 1: Dokumentation](https://docs.typo3.org/m/typo3/reference-tsconfig/10.4/en-us/PageTsconfig/TceForm.html)
[Referenz 2: Random Website](https://www.econcess.de/blog/typo3-programmierung/230-typo3-neues-frontend-layout-fuer-aenderungen-im-header)
[Referenz 3: Random Website](http://www.pi-phi.de/191.html)
[Referenz 4: Random Website](https://www.typo3-lisardo.de/home/tags/tceform.html)
[Referenz 5: Stackoverflow](https://stackoverflow.com/questions/9736951/how-to-add-a-new-template-to-typo3-layouts-drop-down-list)

**Comment by dimitristaufer** [comment]
Thank you! That helped 🎉 May I buy you a coffee?

Also, if you don't mind answering another layout-specific question in this issue. I am trying to work with backend layouts and have defined a basic two column backend layout in Typo3. As described in the [documentary](https://typo3-initiatives.github.io/nuxt-typo3/frontend/backend-layouts.html#create-backend-layout-component) my JSON Api returns

`{
  ...
  "content": {
    "colPos0": [...Array with content elements],
    "colPos1": [...Array with content elements]
  }
  ...
}
`

[This](http://akiko-nojiri.de/STRATO-apps/typo3_01/app/home) is my test JSON page.

I also followed the instructions in the documentation and added a "Be2columns.vue" component and registered the backend layouts. Now I am not sure what to do, because only the left column is showing up. I tried using the "Be2columns" component in my "default.vue" layout, but then I get a type error `Cannot read property 'colPos0' of undefined `. Thanks in advance.

**Comment by kubilaymelnikov** [comment]
I'm happy to do that! 

Your output is not correct or your Be Layout Component have wrong name.

This is your output:
```
"appearance": {
  "layout": "layout-0",
  "backendLayout": "1",
  "backendLayoutNextLevel": "",
  "newUntil": "0"
}
```

You take the string in `backendLayout` and put a Be in front of it in camelcase notation.
Than you have this file name `Be1.vue`, nuxt-typo3 uses this automatically.
Or you name your BackendLayout correctly:
```
mod.web_layout.BackendLayouts {
  Main {
    title = 2columns
    name = 2columns
    config {
      backend_layout {
        colCount = 2
        rowCount = 1
        rows {
          1 {
            columns {
              1 {
                name = Left
                colPos = 0
                colspan = 1
              }

              2 {
                name = Right
                colPos = 1
                colspan = 1
              }
            }
          }
        }
      }
    }
  }
}
```

You dont have to change anything in your `default.vue`:
```
<template>
  <div class="default">
    <nuxt />
  </div>
</template>
```

You can follow all this in the code, here is the sequence:
https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/6bde261c1ee20809f633f92ff5080f590031d3fe/lib/templates/middleware/context.js#L24-L27

https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/f2f63cafc4f319b6d91dfc56c8248006251c089e/lib/templates/lib/layouts.js#L7-L27

https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/6bde261c1ee20809f633f92ff5080f590031d3fe/lib/templates/mixins/page/default.js#L10-L17

https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/f2f63cafc4f319b6d91dfc56c8248006251c089e/lib/templates/pages/_.vue#L3-L7

https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/6bde261c1ee20809f633f92ff5080f590031d3fe/lib/templates/layouts/backend/BeDynamic.js#L30-L36

**Comment by dimitristaufer** [comment]
Thank you for your help. Especially for providing the inner-workings of the layout generation.

For some reason, I am unable to edit the _PageTS-Config_ in my TYPO3 Backend. The following screenshot shows all the options I have. Somehow, I am only given a graphical config editor and cannot change the code, thus I am unable to e.g. change the _title_.

Any ideas?

![Screen Shot 2021-08-01 at 11 08 54](https://user-images.githubusercontent.com/44700468/127765744-108dd617-1990-4ba4-9cb0-cc7137446c2a.png)
