### ISSUE TITLE
Deployment SSL issues

### ISSUE THREAD

**Issue by fvonellerts** [TYPO3-Initiatives/nuxt-typo3#15]
We usually serve our TYPO3 sites using MAMP.
With a virtual host it is possible to point the frontend domain to the nuxt Node.js server:
```
ServerAlias frontend.host.com
SSLProxyEngine On
ProxyPass / http://localhost:3000/
ProxyPassReverse / http://localhost:3000/
```
...and connect it to the backend using the following code in `nuxt.config.js`:
```
typo3: {
    baseURL: 'http://localhost:3000/',
    api: {
        baseURL: 'http://cms.host.com/'
    }
}
```

This is working so far. But of course we would like to use SSL for both the front- and backend.
So we add certificates (not self-signed) to the MAMP hosts and edit the `typo3.api.baseURL` in `nuxt.config.js`.
However when running the nuxt server, this error now appears and every page returns a 500 error:

```
 ERROR  Cannot read property 'url' of undefined                       12:15:01

  at server.js:1:107167
  at processTicksAndRejections (internal/process/task_queues.js:94:5)
  at async Store.nuxtServerInit (server.js:1:104573)
  at async t.default (server.js:1:115600) (repeated 1 times)
```

We tried changing `typo3.baseURL` with no success... The error only comes up once the API uses SSL. And if only the frontend uses SSL, the site loads but XMLRequests to the API are blocked.

Any ideas?

**Comment by mercs600** [comment]
@fvonellerts if you enter your API host (with https) in the browser - is the url trusted ? This is important for connection between nodejs and API. 

In other case when certificate is invalid (is not trusted by browser) you can do some workaround and setup NODE env variable:
```
NODE_TLS_REJECT_UNAUTHORIZED=0
```

But remember this is only workaround, this setting should be avoided on production env. 

https://stackoverflow.com/questions/10888610/ignore-invalid-self-signed-ssl-certificate-in-node-js-with-https-request

**Comment by fvonellerts** [comment]
@mercs600 Thanks for the quick answer. The certificate is not self-signed and trusted by the browser.

**Comment by mercs600** [comment]
@fvonellerts you write: `site loads but XMLRequests to the API are blocked.` you mean the first load of page ( by server side ) is ok, then ajax request not ?

**Comment by fvonellerts** [comment]
@mercs600 Yes exactly. The console states `Mixed Content: The page at 'https://frontend.host.com' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://cms.host.com'. This request has been blocked; the content must be served over HTTPS.`.

**Comment by mercs600** [comment]
@fvonellerts so it might be the issue your API should works also on https. Second issue you may face is the CORS policy, your API host should returns header `Access-Control-Allow-Origin:` for your frontend domain.

**Comment by mercs600** [comment]
@fvonellerts did you resolved issue with mixed content ?

**Comment by fvonellerts** [comment]
@mercs600 Somehow the problem did not arise again on the live server, so I guess it may be some error with the dev VirtualHost config or the wildcard certificate. Thanks for your help!
