### ISSUE TITLE
remove registerBackendLayouts function

### ISSUE THREAD

**Issue by mercs600** [TYPO3-Initiatives/nuxt-typo3#166]
we can move this function https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/master/lib/templates/middleware/context.js#L24 
to `BeDynamic`
 then we can remove it 
https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/master/lib/templates/plugins/layouts.js#L5 
Now we check `context.app.components` too fast, so thats why we have to use `registerBackendLayouts` to register backend layout components - it was useful only for checking and confirming that the backend layout which we want to load exist in components array.

**Comment by mohitsaxenaknoldus** [comment]
Please assign it to me, I'll do it.
