### ISSUE TITLE
ERR_STORE_NOT_PROVIDED with vuex-module-decorators

### ISSUE THREAD

**Issue by larsalbrecht** [TYPO3-Initiatives/nuxt-typo3#196]
I have a nuxt 2 (typescript) project that uses vuex-module-decorators (https://github.com/championswimmer/vuex-module-decorators). 

If I install nuxt-typo3 and add all configuration to nuxt.config.js, I only got the following error in frontend:
`ERR_STORE_NOT_PROVIDED: To use getModule(), either the module should be decorated with store in decorator, i.e. @Module({store: store}) or store should be passed when calling getModule(), i.e. getModule(MyModule, this.$store)
`

[The nuxt-auth](https://auth.nuxtjs.org/) plugin seems to have a [simliar problem](https://github.com/championswimmer/vuex-module-decorators/issues/227). The workaround here is to disable vuex. Have you a better one for your plugin?

**Comment by mercs600** [comment]
@larsalbrecht I see a lot of plugins face with this issue, could you reproduce repository with that ?
I have created nuxt project with nuxt and vuex decorators and not see any issues at the moment, but propably I dont know your context -> https://github.com/mercs600/nuxt-typo3-vuex-decorators.

**Comment by larsalbrecht** [comment]
It seems you are missing the store-accessor:
https://github.com/championswimmer/vuex-module-decorators#accessing-modules-with-nuxtjs
Sorry I did not mention this. If you can't reproduce it now, I will build you a clean small project tomorrow.

**Comment by mercs600** [comment]
I have upgraded repository with accessor, still works. I think you should be able to override typo3 store module to add ts annotation.

**Comment by larsalbrecht** [comment]
I found the issue! It's not your issue. 
I import stores in a plugin, and that causes the issue in combination with nuxt-typo3.

Thank you for your time!
