### ISSUE TITLE
Handling empty pages

### ISSUE THREAD

**Issue by boneyfantaseas** [TYPO3-Initiatives/nuxt-typo3#218]
Pages created in TYPO3 without any content currently throw console errors due to the prop types defined within T3BlDefault.vue and T3Dynamic.vue

- https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/b3b7cde9fb42096a5994b02fb14a057e34817633/lib/components/T3BlDefault/T3BlDefault.vue#L14
- https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/b3b7cde9fb42096a5994b02fb14a057e34817633/lib/components/T3Dynamic/T3Dynamic.js#L14

I think there should be no error message on empty pages in the first place, so I wonder if the types should rather be **[Object, Array]** or if the implementation in TYPO3 should be different.

**Comment by mercs600** [comment]
@boneyfantaseas you are right. Because of inconsistent API responses we have to handle two types on the frontend. I have fixed it, but in the long run, we have to fix it on the API side.
