### ISSUE TITLE
FeLogin - recent commits and typo3 11.5

### ISSUE THREAD

**Issue by janslu** [TYPO3-Initiatives/nuxt-typo3#221]
I'm trying to get FeLogin to work on with a master branch of this repo ([just merged FeLogin support](https://github.com/TYPO3-Initiatives/nuxt-typo3/pull/219)) and typo3 11.5 and ran into the following issues: 

1. typo3 json with a login form is nested deeper - it's this.data.form.fields.pages and not this.data.form.fields (line 41-43 in T3CeFeloginLogin.vue:
```      
elements () {
   return this.compileFormElements(this.data.form.elements || this.data.form.fields.pages)
},
```
2. After form submit I do not get a response with a structure nuxt-typo3 expects in onSubmit method. Response is:
```
"content": {
        "header": "Sign In",
        "subheader": "Join our community",
        "headerLayout": 0,
        "headerPosition": "",
        "headerLink": "",
        "data": "<h3>\n        \nLogin successful\n\n\n    <\/h3>\n\n\nYou are now logged in as &#039;test&#039;"
    }
}
```
nuxt is expecting a status  and a redirectUrl:
```
const { redirectUrl, status } = response.content.data
```
but where are those supposed to come from if the template in EXT:headless is:
```
<f:format.json value="{
            form: {
                title: '{f:translate(key:\'form.login.title\')}',
                action: '{f:uri.action(action:\'login\')}',
                method: 'POST',
                fields: '{f:render(partial: \'LoginFields\', arguments: \'{_all}\') -> headless:format.json.decode()-> headless:loginForm(action:\'login\', name:\'field\') -> headless:format.json.decode()}'
            },
            message: {
                header: '{f:render(partial: \'RenderLabelOrMessage\', arguments: \'{key: \\\'{messageKey}_header\\\'}\')}',
                message: '{f:render(partial: \'RenderLabelOrMessage\', arguments: \'{key: \\\'{messageKey}_message\\\'}\')}'
            },
            recovery: '{f:render(partial: \'Recovery\', arguments: \'{_all}\') -> headless:format.json.decode()}',
            flashMessages: '{f:render(partial: \'FlashMessages\', arguments: \'{_all}\') -> headless:format.json.decode()}'
        }"/>
```
Is there something I'm missing?

**Comment by mercs600** [comment]
@janslu you are right, be aware, we haven't published the current master on npm yet, because the headless ext is not ready. If you want to test it you can use this branch of PWA demo -> https://github.com/TYPO3-Initiatives/pwa-demo/pull/44/files

**Comment by janslu** [comment]
Thank you so much! I missed this, and after pulling
```
"friendsoftypo3/headless": "dev-TASK/Felogin-adjustments",
```
using composer, everything starts to work and rather nice :)

**Comment by mercs600** [comment]
no problem, be aware also the TYPO3 API is responding with set-cookie header, so this cookie has to be setup on the same domain as what the frontend is. For example when your API is working on `api.typo3.com` and frontend on `typo3.com` then the cookie domain has to be setup as `.typo3.com`

**Comment by janslu** [comment]
Thanks! Now I'm looking into getting the logged in/out state when the browser is reloaded and the session is still active. It seems I will have to actively query the backend and get a variable:
```
page.10.fields {
  userIsLoggedIn = TEXT
  userIsLoggedIn.value = 0
}

[frontend.user.isLoggedIn]
page.10.fields {
  userIsLoggedIn.value = 1
}
[end]
```

**Comment by mercs600** [comment]
Right, we consider to add it to initialData. Other solution is parsing request cookie on SSR side and check if felogin cookie exist

**Comment by janslu** [comment]
Sounds good! I am running an additional api.getPage call, to get the value passed in page object, like this:

```
const { $typo3, $viewport } = useContext()
const router = useRouter()
const store = useStore()

onMounted(async () => {
   const { data } = await $typo3.api.getPage(router.currentRoute.path)
   if (parseInt(data?.userIsLoggedIn) === 1) {
      store.commit('SET_USER_STATE', 1)
   } else {
      store.commit('SET_USER_STATE', 0)
   }
})
```
