### ISSUE TITLE
Wrong page title variable in _.vue file

### ISSUE THREAD

**Issue by Moongazer** [TYPO3-Initiatives/nuxt-typo3#35]
In line 3, it must be `<h1>{{ page.page.title }}</h1>` to print the page title.

**Comment by mercs600** [comment]
Thanks @Moongazer We fixed it, this h1 is not necessary there and we removed it, but it is still on develop branch, we haven't released new version yet.

**Comment by Moongazer** [comment]
There is another issue with this page: it seems to be not possible to overwrite nuxt-typo3's `_.vue` by making a copy into `~/pages/_.vue`. The compiler will throw an `Unexpected identifier` error in `server.js` resulting from `NuxtLink`.
The documentation for this page seems to be broken or empty... is there a way to customize the page for content-elements? Or should I do it through custom layout files? Somehow the latter feels a bit odd...

**Comment by mercs600** [comment]
You should be able to override _.vue without any errors. Are you able to show me your _.vue template ?

**Comment by Moongazer** [comment]
Sure, here is what I did:

1) Copy the original `nuxt-typo3/lib/templates/pages/_.vue` file to local project (`~/pages/_.vue`)
2) Adjust the import path for `defaultPage` to `nuxt-typo3/lib/templates/mixins/page/default`
```
<template>
  <div>
    <h1>{{ page.page.title }}</h1>
    <be-dynamic :page="page.page" :content="page.content" :type="backendLayout" />
  </div>
</template>
<script>
import defaultPage from 'nuxt-typo3/lib/templates/mixins/page/default'
export default {
  mixins: [defaultPage]
}
</script>
```
![vue-generic-page-error](https://user-images.githubusercontent.com/1685510/82355743-e91faa00-9a02-11ea-8586-93cc946bce4a.png)

**Comment by mercs600** [comment]
@Moongazer do you have still this issue ? I copy your _.vue file to new project so it overrided _.vue file from nuxt-typo3 and it works 😨 This error might be related with transpiling of node modules - we have to tell to the webpack what modules from node_modules should be transpiled by babel. You can do it by setup transpile in nuxt.config https://nuxtjs.org/api/configuration-build/#transpile 

```js
  build: {
...
    transpile: ['nuxt-typo3'],
...
```

**Comment by Moongazer** [comment]
I think the `transpile: ['nuxt-typo3']` did the trick, thanks a lot!

**Comment by MichaelNussbaumerGOWEST** [comment]
Transpile doesn't help in my case. It worked before. 

Any tips?

We just modified the extendRoutes function in nuxt-typo3 for now:

 ```
 // add default _.vue page to handle dynamic routing
  this.extendRoutes((routes, resolve) => {
    const pageRoutes = routes.filter(route => route.path === '/*');
    if(pageRoutes.length === 0) {
      routes.push({
        name: 'page',
        path: '/*',
        component: resolve(__dirname, './templates/pages/_.vue')
      })
    }
  })
```

We cannot override the function vie nuxt.conf.js router as the route is added afterwards.

**Comment by mercs600** [comment]
@MichaelNussbaumerGOWEST are you able to provide some repository with your current configuration ? I will try to help you, because page override should works out of the box.

**Comment by MichaelNussbaumerGOWEST** [comment]
@mercs600 let me know how I can send you the Repo .zip.

**Comment by mercs600** [comment]
@MichaelNussbaumerGOWEST could you create some private repository on GitHub or some where else ? In that case I could point for you places you can fix in the code.

**Comment by MichaelNussbaumerGOWEST** [comment]
@mercs600 sent u an invite to a copy of the private repo

**Comment by mercs600** [comment]
@MichaelNussbaumerGOWEST I found out what was the issue - I put comment in nuxt.config.js

for others:
if you used nuxt-i18n please remember about setup strategy to "no_prefix" 
https://typo3-initiatives.github.io/nuxt-typo3/configuration/i18n.html 
https://i18n.nuxtjs.org/routing

because nuxt-i18n overrides default path, but in our case for the whole routing (event with language code) is responsible typo3 API

**Comment by MichaelNussbaumerGOWEST** [comment]
@mercs600 thank you for the review, it works now.
