### ISSUE TITLE
felogin integration 

### ISSUE THREAD

**Issue by mercs600** [TYPO3-Initiatives/nuxt-typo3#40]
integration with backend, possibility to sign-up/sign in, check cookies context 

related to: https://github.com/TYPO3-Initiatives/headless/issues/119

The main goal is:
1. use the T3Form components we have implemented in alpha version. 
2. then we have to prepare login forms
3. login action handling - we should refresh initialData for the logged-in user - usually we have some additional data for the current user - for example to display something in navigation. 
4. we need some global flag/getter to detect if a user is logged-in (useful for authenticating routes and content elements)

**Comment by MichaelNussbaumerGOWEST** [comment]
Any info about the status this?

**Comment by mercs600** [comment]
The main goal is:
1. use the T3Form components we have implemented in alpha version. 
2. then we have to prepare login/register forms
3. login action handling - we should refresh initialData for the logged-in user - usually we have some additional data for the current user - for example to display something in navigation.
