### ISSUE TITLE
Nuxt components to override nuxt-typo3 components

### ISSUE THREAD

**Issue by mercs600** [TYPO3-Initiatives/nuxt-typo3#44]
Check possibility and add documentation how to override nuxt-typo3 components by https://github.com/nuxt/components. 

Right now we have to import our custom components and register them as global components: 
https://typo3-initiatives.github.io/nuxt-typo3/from-scratch/3-customization.html#_2-2-register-your-component.

There is package which can do the same thing, but there is no need to import them and register manually, you can do it with nuxt/components by: 

```
// nuxt.config.js
export default {
  components: [
    { path: '~/components', extensions: ['vue'] }
  ]
}
```

**Comment by CasianBlanaru** [comment]
I was able to tackle this theme

**Comment by CasianBlanaru** [comment]
Has been tested and currently doesn't work 100% 
with functional components.
