### ISSUE TITLE
Extra payloads for asyncData

### ISSUE THREAD

**Issue by Aliath** [TYPO3-Initiatives/nuxt-typo3#59]
Hi, let's assume that we have a TYPO page that uses custom content elements. Some elements are kinda-sorta dynamic, it means them require some extra data from server to display the right way and so on. There's no problem to fetch the data immadiately after the page is rendered client-side, but it would be also great to display this content on server-side. The main problem is about how does asyncData works for now - it does not allow us to get some extra stuff from the server.

Well, the question is: is there any possibility to inject additional handler to asyncData?

**Comment by Aliath** [comment]
I can suggest the solution - we can add option property that determines if plugin should use it's default `_.vue` page or just define custom `_.vue` page that extends `mixins/page/default.js` - thereby we can define custom extra payloads for asyncData and use imported typo-components as well.

**Comment by mercs600** [comment]
@Aliath exactly, you can override _.vue file in your project and add custom logic for your asyncData there. 
Just create _.vue file in your project and add:

```
 asyncData({ pageContent, backendLayout }) {
    // your custom logic here 
    if (pageContent) {
      return {
        page: pageContent,
        backendLayout
      }
    }
  }
```

in the other hand, if you want to do something extra with request you can copy content of middleware (which is responsible for deliver asyncData) to asyncData of your _.vue file 
https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/master/lib/templates/middleware/context.js 

The second option is you can use fetch method https://nuxtjs.org/api/pages-fetch/ - it works on SSR also. 

Is is helpful for you ?

**Comment by Aliath** [comment]
@mercs600  that's right, but I don't want to override files inside node_modules 😄 .

What about just make the default plugin's routing disabled by options? #60

**Comment by mercs600** [comment]
@Aliath you don't have to, just create _.vue file inside of your project in page directory (not plugin directory) - it should override _.vue file from plugin out of the box ;-) 

I think it should resolve your issue, without #60 changes

**Comment by Aliath** [comment]
@mercs600 uh, this seems work 😄 Thank you!
