### ISSUE TITLE
Inserting link[rel="canonical"]

### ISSUE THREAD

**Issue by Aliath** [TYPO3-Initiatives/nuxt-typo3#61]
Hello again. 😄
I have noticed something weird with link[rel="canonical"] added to the website. Let's start from beggining - response of initial request from the page below:
![image](https://user-images.githubusercontent.com/28493823/89026892-c1fe2680-d329-11ea-96ac-8343defdd70e.png)
The _canonical_ property is just empty string, but [the code uses](https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/master/lib/templates/mixins/seo/getMeta.js#L39) String.prototype.link property, which always exists and the value of it's length is always 1. It causes following problem:
![image](https://user-images.githubusercontent.com/28493823/89027130-42248c00-d32a-11ea-9033-021dbf8a45a9.png)

I have not used this property in my project so far so I do not know what is the response of existing canonical tag but there are two options - the first is that canonical property is just string. The second is that canonical property is string in case it's empty, otherwise it's object with link property. In both cases we have to handle this the right way.

**Comment by mercs600** [comment]
thank you @Aliath for the investigation - fixed
