### ISSUE TITLE
API errors handling

### ISSUE THREAD

**Issue by Aliath** [TYPO3-Initiatives/nuxt-typo3#62]
In file [lib/templates/middleware/context.js](https://github.com/TYPO3-Initiatives/nuxt-typo3/blob/master/lib/templates/middleware/context.js#L7) we have condition that check if the fields from API response exists, but in case we have e.g. 404 error - the response will be undefined and calling response.data will crash function callee.

Suggested solution: replace `if (response.data && response.data.page)` with `if (response && response.data && response.data.page)`. This way the app will render error page if it exists, not the nuxt call stack.

**Comment by mercs600** [comment]
Thank you for that 👏
