### ISSUE TITLE
Axios error handling "Cannot read property 'url' of undefined"

### ISSUE THREAD

**Issue by Prizzler** [TYPO3-Initiatives/nuxt-typo3#85]
Hi,

unfortunately I can't give you code to reproduce, because it is an server issue. On my devsystem I run a server with a self signed ssl certificate.

therefore I get the error "unable to verify the first certificate". I know how to fix the issue, but it was hard to track down because, nuxt-typo3 give me the error "Cannot read property 'url' of undefined".

the problem for that is the axios error handling in lib/api.js and plugin/api.js.

ib/api.js

```js
  getInitialData(
    params = {
      path: ''
    }
  ) {
    return this.$http
      .get(`${params.path}/${this.options.endpoints.initialData}`)
      .catch(error => {
        consola.info('Check your API host: ', error.config.url)
        consola.error(new Error(error))
        throw error
      })
  }
```

plugin/api.js

```js
  api.$http.onError(error => {
    if (
      error.response.status === 404 &&
      error.config.url &&
      error.config.url.includes(options.api.endpoints.initialData)
    ) {
      return api.getInitialData({
        path: getLocaleCodePath(context)
      })
    }
  })
```

please use a more generic error handling like:

```js
axios.get(endpint)
  .catch(function (error) {
    if (error.response) {
      // The request was made and the server responded with a status code
      // that falls out of the range of 2xx
      console.log(error.response.data);
      console.log(error.response.status);
      console.log(error.response.headers);
    } else if (error.request) {
      // The request was made but no response was received
      // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
      // http.ClientRequest in node.js
      console.log(error.request);
    } else {
      // Something happened in setting up the request that triggered an Error
      console.log('Error', error.message);
    }
    console.log(error.config);
  });
```

cheers p.

**Comment by mercs600** [comment]
@Prizzler it should be fixed with 0.9.0 version. Now you should get straight information what is wrong with the connection. Unfortunately onError interceptor is needed for getting initialData for 404 pages - because endpoint ?type=834 is not available for these 404 pages - so as as fallback for initialData request on 404- we just getting data from homepage.
